version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: adestramento_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
      timeout: 20s
      retries: 10
      interval: 5s

  api:
    build: .
    container_name: adestramento_api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DB_HOST: db
      DB_USER: root                 # ← Usuário root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: